# Generated by Django 4.1 on 2022-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('complete', models.BooleanField(verbose_name='Complete')),
                ('description', models.TextField(verbose_name='Des')),
            ],
        ),
    ]
