# Generated by Django 4.1 on 2022-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdet',
            name='complete',
            field=models.BooleanField(blank=True, null=True, verbose_name='Complete'),
        ),
        migrations.AlterField(
            model_name='eventdet',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
